### ISSUE TITLE
Build Error an Makefile Patch.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [DCurrent/openbor#253]
+ export 'CFLAGS=-O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC' 'CXXFLAGS=-O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC'
+ CFLAGS='-O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC'
+ CXXFLAGS='-O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC'
+ pushd engine
~/testing/BUILD/openbor-7142/engine ~/testing/BUILD/openbor-7142
+ ./version.sh
+ ./environ.sh 4
-------------------------------------------------------
   Linux  SDK (x86_64-unknown-linux-gnu) Environment Loaded!
-------------------------------------------------------
+ /usr/bin/make -j4 SDKPATH=/usr LNXDEV=/usr/bin BUILD_LINUX=1 GCC_TARGET=amd64
Compiling LINUX Port: openbor.c...
Compiling LINUX Port: openborscript.c...
Compiling LINUX Port: sdl/joysticks.c...
Compiling LINUX Port: sdl/control.c...
openborscript.c: In function 'openbor_getgfxproperty':
openborscript.c:14920:21: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                     v = (LONG)(((unsigned short *)screen->data)[y * screen->width + x]);
                     ^
openborscript.c:14923:21: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                     v = (LONG)(((unsigned *)screen->data)[y * screen->width + x]);
                     ^
Compiling LINUX Port: sdl/sblaster.c...
Compiling LINUX Port: sdl/timer.c...
Compiling LINUX Port: sdl/sdlport.c...
Compiling LINUX Port: sdl/video.c...
Compiling LINUX Port: sdl/videocommon.c...
Compiling LINUX Port: sdl/threads.c...
Compiling LINUX Port: sdl/menu.c...
Compiling LINUX Port: sdl/opengl.c...
Compiling LINUX Port: sdl/loadgl.c...
Compiling LINUX Port: source/adpcmlib/adpcm.c...
Compiling LINUX Port: source/gfxlib/2xSaI.c...
Compiling LINUX Port: source/gfxlib/bilinear.c...
Compiling LINUX Port: source/gfxlib/dotmatrix.c...
cc1: all warnings being treated as errors
Compiling LINUX Port: source/gfxlib/gfx.c...
make: *** [Makefile:667: openborscript.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by Zombie-Ryushu** [comment]
[openbor-3.0.6391-fix-Makefile.txt](https://github.com/DCurrent/openbor/files/7795451/openbor-3.0.6391-fix-Makefile.txt)

**Comment by msmalik681** [comment]
[https://github.com/DCurrent/openbor/tree/global_beta](https://github.com/DCurrent/openbor/tree/global_beta) this is the branch you should be compiling from please test this one and confirm if it is working for you. If not please give more details about your system.

**Comment by Zombie-Ryushu** [comment]
~/testing/BUILD/openbor-global_beta/engine ~/testing/BUILD/openbor-global_beta
+ ./version.sh
Missing version build, please add it manually and press ENTER: 

Missing version commit, please add it manually and press ENTER: 

VERSION_BUILD is set to: 
VERSION_COMMIT is set to: 
+ ./environ.sh 4
-------------------------------------------------------
   Linux  SDK (x86_64-unknown-linux-gnu) Environment Loaded!
-------------------------------------------------------
+ /usr/bin/make -j4 SDKPATH=/usr LNXDEV=/usr/bin BUILD_LINUX=1 GCC_TARGET=amd64
Compiling LINUX Port: openbor.c...
Compiling LINUX Port: openborscript.c...
Compiling LINUX Port: sdl/control.c...
Compiling LINUX Port: sdl/sblaster.c...
openborscript.c: In function 'openbor_getgfxproperty':
openborscript.c:15152:21: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                     v = (LONG)(((unsigned short *)screen->data)[y * screen->width + x]);
                     ^
openborscript.c:15155:21: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                     v = (LONG)(((unsigned *)screen->data)[y * screen->width + x]);
                     ^
Compiling LINUX Port: sdl/timer.c...
Compiling LINUX Port: sdl/sdlport.c...
Compiling LINUX Port: sdl/video.c...
Compiling LINUX Port: sdl/videocommon.c...
Compiling LINUX Port: sdl/threads.c...
Compiling LINUX Port: sdl/menu.c...
Compiling LINUX Port: sdl/opengl.c...
openborscript.c: At top level:
cc1: error: unrecognized command line option '-Wno-stringop-truncation' [-Werror]
cc1: error: unrecognized command line option '-Wno-format-truncation' [-Werror]
cc1: all warnings being treated as errors

**Comment by Zombie-Ryushu** [comment]
This is an older (obsolete) Rosa Linux 2016.1 System running gcc 5.5

**Comment by msmalik681** [comment]
Compile a more recent version of gcc i think at least 7 should be good.

If you dont want to upgrade your system i suggest to use a virtual machine just for compiling like lubuntu or mx linux.

Closing this down as your version of gcc is clearly the issue and i have confirmed everything working on pop os 20.04
