### ISSUE TITLE
error compiling on Ubuntu 20.04

### ISSUE THREAD

**Issue by erod20** [DCurrent/openbor#200]
I keep this error when compiling on Ubuntu 20.04

ource/gamelib/packfile.c:322:31: error: ‘%s’ directive writing up to 255 bytes into a region of size between 0 and 511 [-Werror=format-overflow=]
  322 |         sprintf(fullpath, "%s/%s", dir, entry->d_name);
      |                               ^~
In file included from /usr/include/stdio.h:867,
                 from source/gamelib/packfile.c:29:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 2 and 768 bytes into a destination of size 512
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/string.h:495,
                 from /usr/include/SDL2/SDL_stdinc.h:60,
                 from /usr/include/SDL2/SDL_main.h:25,
                 from /usr/include/SDL2/SDL.h:32,
                 from sdl/video.h:15,
                 from openbor.h:23,
                 from openbor.c:14:
In function ‘strncpy’,
    inlined from ‘savelevelinfo’ at openbor.c:36372:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ output may be truncated copying 50 bytes from a string of length 1471 [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:668: source/gamelib/packfile.o] Error 1
make: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
make: *** [Makefile:667: openbor.o] Error 1

Removing All LINUX Files...
Done!

**Comment by msmalik681** [comment]
try "sudo apt-get install libsdl2-dev libsdl2-gfx-dev libpng-dev libvorbis-dev libvpx-dev"

**Comment by erod20** [comment]
All the dependencies are installed. It builds fine on 18.04 but not 20.04.

**Comment by sdsddsd1** [comment]
This seems like an issue with gcc9. See [here](http://www.chronocrash.com/forum/index.php?topic=4530.0)

**Comment by danielt3** [comment]
It builds fine in GCC 8.3.0 (Debian 10). The command line given by @msmalik681 works fine (the wiki needs a small fix since it says to install `libpng12-dev` which is not included in Debian 10). I just built and run with libpng-dev and saw no notable issues.

I will try to install GCC-9 on my box and fix the errors.

**Comment by danielt3** [comment]
> 
> 
> It builds fine in GCC 8.3.0 (Debian 10). The command line given by @msmalik681 works fine (the wiki needs a small fix since it says to install `libpng12-dev` which is not included in Debian 10). I just built and run with libpng-dev and saw no notable issues.
> 
> I will try to install GCC-9 on my box and fix the errors.

I didn't try to build the 32bit version, only the 64bit which is the native in my system.

**Comment by spilinek** [comment]
I was able to workaround this by updating Makefile. Replace **-Werror** with **-Wno-error**

**Comment by danielt3** [comment]
That is not the kind of solution I like the most. Someone have enabled -Werror and there is HUGE motivation about this. We might lose our compiler-buddy to help finding bugs we miss. I'd say if it is *really* *really* needed to use GCC9, to accept this as a TEMPORARY solution but I'd STRONGLY recommend to fix these properly and re-enable -Werror.

I didn't had the time to test in my own box here (it is a Debian VM). Likely I will do so this afternoon.

**Comment by spilinek** [comment]
There's 4 warnings:

-------------------------------------------------------
OpenBOR v3.0 Build 7086 (commit hash: 7a45a22) - http://www.ChronoCrash.com

All rights reserved.
See LICENSE and README within OpenBOR root for details.

Copyright (c) 2004 - 2018 OpenBOR Team
-------------------------------------------------------
-------------------------------------------------------
   Linux amd64 SDK (x86_64-linux-gnu) Environment Loaded!
-------------------------------------------------------

Removing All LINUX Files...
Done!

Compiling LINUX Port: openbor.c...
Compiling LINUX Port: openborscript.c...
Compiling LINUX Port: sdl/joysticks.c...
Compiling LINUX Port: sdl/control.c...
Compiling LINUX Port: sdl/sblaster.c...
Compiling LINUX Port: sdl/timer.c...
Compiling LINUX Port: sdl/sdlport.c...
Compiling LINUX Port: sdl/video.c...
Compiling LINUX Port: sdl/videocommon.c...
Compiling LINUX Port: sdl/threads.c...
Compiling LINUX Port: sdl/menu.c...
Compiling LINUX Port: sdl/opengl.c...
Compiling LINUX Port: sdl/loadgl.c...
Compiling LINUX Port: source/adpcmlib/adpcm.c...
Compiling LINUX Port: source/gfxlib/2xSaI.c...
Compiling LINUX Port: source/gfxlib/bilinear.c...
Compiling LINUX Port: source/gfxlib/dotmatrix.c...
Compiling LINUX Port: source/gfxlib/gfx.c...
Compiling LINUX Port: source/gfxlib/hq2x.c...
Compiling LINUX Port: source/gfxlib/scale2x.c...
Compiling LINUX Port: source/gfxlib/scanline.c...
Compiling LINUX Port: source/gfxlib/simple2x.c...
Compiling LINUX Port: source/gfxlib/tv2x.c...
Compiling LINUX Port: source/gamelib/draw.c...
Compiling LINUX Port: source/gamelib/draw16.c...
Compiling LINUX Port: source/gamelib/draw32.c...
Compiling LINUX Port: source/gamelib/font.c...
Compiling LINUX Port: source/gamelib/translation.c...
Compiling LINUX Port: source/gamelib/anigif.c...
Compiling LINUX Port: source/gamelib/bitmap.c...
Compiling LINUX Port: source/gamelib/screen.c...
Compiling LINUX Port: source/gamelib/screen16.c...
Compiling LINUX Port: source/gamelib/screen32.c...
Compiling LINUX Port: source/gamelib/loadimg.c...
Compiling LINUX Port: source/gamelib/palette.c...
Compiling LINUX Port: source/gamelib/packfile.c...
Compiling LINUX Port: source/gamelib/filecache.c...
In file included from /usr/include/string.h:495,
                 from /usr/include/SDL2/SDL_stdinc.h:60,
                 from /usr/include/SDL2/SDL_main.h:25,
                 from /usr/include/SDL2/SDL.h:32,
                 from sdl/video.h:15,
                 from openbor.h:23,
                 from openbor.c:14:
In function ‘strncpy’,
    inlined from ‘savelevelinfo’ at openbor.c:36372:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output may be truncated copying 50 bytes from a string of length 1471 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source/gamelib/packfile.c: In function ‘casesearch’:
source/gamelib/packfile.c:322:31: warning: ‘%s’ directive writing up to 255 bytes into a region of size between 0 and 511 [-Wformat-overflow=]
  322 |         sprintf(fullpath, "%s/%s", dir, entry->d_name);
      |                               ^~
In file included from /usr/include/stdio.h:867,
                 from source/gamelib/packfile.c:29:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 2 and 768 bytes into a destination of size 512
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling LINUX Port: source/gamelib/pixelformat.c...
Compiling LINUX Port: source/gamelib/soundmix.c...
Compiling LINUX Port: source/gamelib/spriteq.c...
Compiling LINUX Port: source/gamelib/sprite.c...
Compiling LINUX Port: source/gamelib/spritex8p16.c...
Compiling LINUX Port: source/gamelib/spritex8p32.c...
Compiling LINUX Port: source/gamelib/models.c...
Compiling LINUX Port: source/gamelib/transform.c...
Compiling LINUX Port: source/gamelib/filters.c...
Compiling LINUX Port: source/stringptr.c...
Compiling LINUX Port: source/utils.c...
Compiling LINUX Port: source/stristr.c...
Compiling LINUX Port: source/omath.c...
Compiling LINUX Port: source/scriptlib/StackedSymbolTable.c...
Compiling LINUX Port: source/scriptlib/ScriptVariant.c...
Compiling LINUX Port: source/scriptlib/SymbolTable.c...
Compiling LINUX Port: source/scriptlib/Instruction.c...
Compiling LINUX Port: source/scriptlib/Interpreter.c...
Compiling LINUX Port: source/scriptlib/ImportCache.c...
Compiling LINUX Port: source/scriptlib/ParserSet.c...
Compiling LINUX Port: source/scriptlib/Parser.c...
Compiling LINUX Port: source/scriptlib/Lexer.c...
Compiling LINUX Port: source/scriptlib/Stack.c...
Compiling LINUX Port: source/scriptlib/List.c...
Compiling LINUX Port: source/preprocessorlib/pp_lexer.c...
Compiling LINUX Port: source/preprocessorlib/pp_parser.c...
Compiling LINUX Port: source/preprocessorlib/pp_expr.c...
In file included from /usr/include/string.h:495,
                 from source/globals.h:17,
                 from source/scriptlib/depends.h:13,
                 from source/scriptlib/List.h:28,
                 from source/preprocessorlib/pp_parser.c:24:
In function ‘strncat’,
    inlined from ‘pp_parser_stringify’ at source/preprocessorlib/pp_parser.c:717:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:136:10: warning: ‘__builtin___strncat_chk’ output may be truncated copying 1 byte from a string of length 128 [-Wstringop-truncation]
  136 |   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling LINUX Port: source/openborscript/commands.c...
Compiling LINUX Port: source/openborscript/animation.c...
Compiling LINUX Port: source/openborscript/axis.c...
Compiling LINUX Port: source/openborscript/binding.c...
Compiling LINUX Port: source/openborscript/drawmethod.c...
Compiling LINUX Port: source/openborscript/collision_attack.c...
Compiling LINUX Port: source/openborscript/collision_body.c...
Compiling LINUX Port: source/openborscript/collision_entity.c...
Compiling LINUX Port: source/openborscript/constants.c...
Compiling LINUX Port: source/openborscript/entity.c...
Compiling LINUX Port: source/openborscript/index.c...
Compiling LINUX Port: source/openborscript/layer.c...
Compiling LINUX Port: source/openborscript/level.c...
Compiling LINUX Port: source/openborscript/math.c...
Compiling LINUX Port: source/openborscript/recursive_damage.c...
Compiling LINUX Port: source/openborscript/string.c...
Compiling LINUX Port: source/ramlib/ram.c...
Compiling LINUX Port: source/randlib/rand32.c...
Compiling LINUX Port: source/pnglib/pngdec.c...
Compiling LINUX Port: source/pnglib/savepng.c...
Compiling LINUX Port: source/webmlib/vidplay.c...
Compiling LINUX Port: source/webmlib/vorbis.c...
Compiling LINUX Port: source/webmlib/samplecvt.c...
Compiling LINUX Port: source/webmlib/yuv.c...
Compiling LINUX Port: source/webmlib/halloc/halloc.c...
Compiling LINUX Port: source/webmlib/nestegg/nestegg.c...

Linking LINUX Port: OpenBOR.elf...
Stripping LINUX Port: OpenBOR...

Completed LINUX Port!
OpenBOR is now ready!

moved binary to ./releases/LINUX_AMD64/ !

Removing All LINUX Files...
Done!

**Comment by danielt3** [comment]
These are likely easy to fix. They seem to be least. I will take a look.

**Comment by danielt3** [comment]
I fixed the build breaks but I can't push a branch with the fix. Could anyone help me?

**Comment by msmalik681** [comment]
@danielt3 Sure i will do it tomorrow. Thanks for the support.

**Comment by msmalik681** [comment]
@danielt3 sorry but I can not find your branch. what you need to do is make a branch from master apply your fixes then do a pull request to master it will be reviewed if there are no issues DC will add it to master.

**Comment by danielt3** [comment]
I already did. I can't push to the repository.

**Comment by danielt3** [comment]
I'm still getting this error:

```
johndoe@debian-generic:~/devel/openbor-git/engine$ git push -u origin bugfix/fix-gcc9-build-breaks 
Username for 'https://github.com': danielt3
Password for 'https://danielt3@github.com': 
remote: Permission to DCurrent/openbor.git denied to danielt3.
fatal: unable to access 'https://github.com/DCurrent/openbor.git/': The requested URL returned error: 403
```

**Comment by msmalik681** [comment]
Think @DCurrent needs to give you access.

**Comment by danielt3** [comment]
OK. I will keep checking. Thank you.

**Comment by DCurrent** [comment]
@danielt3 you have access to create branches, but you cannot push directly to master - no one can. You need to create a pull request. Then I will review and assuming there's no issues, approve it.

**Comment by danielt3** [comment]
Do you mind checkin again, please. I'm still getting the same error.
```
johndoe@debian-generic:~/devel/openbor-git$ git status
On branch bugfix/fix-gcc9-build-breaks
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	engine/openbor.geany

nothing added to commit but untracked files present (use "git add" to track)
johndoe@debian-generic:~/devel/openbor-git$ git push -u origin bugfix/fix-gcc9-build-breaks 
Username for 'https://github.com': danielt3
Password for 'https://danielt3@github.com': 
remote: Permission to DCurrent/openbor.git denied to danielt3.
fatal: unable to access 'https://github.com/DCurrent/openbor.git/': The requested URL returned error: 403
johndoe@debian-generic:~/devel/openbor-git$ 
```

**Comment by DCurrent** [comment]
@danielt3 sorry to take so long. I just reviewed again and you should have permission to create branches. have you tried to create and modify a branch directly from Github? That would let me know for sure if it's on my end or yours.

**Comment by danielt3** [comment]
Not a problem. Take your time.

I don't think I can create branches directly in Github's Web Interface. Please, see next screenshots. If I can give a tip, likely I can't *push* a branch not create one. Push permissions are handled in a different place in some Git instances.

![image](https://user-images.githubusercontent.com/1739215/85795812-477d2e00-b70f-11ea-94d6-eafffc76c441.png)

![image](https://user-images.githubusercontent.com/1739215/85795924-7398af00-b70f-11ea-840c-2979f6fc91bf.png)

Second image clearly shows I can create a branch directly on the web interface, while I can't in the first one. What else can I do to test this? I wonder if there is something with the branch name I used or something else. I will do some testing.

**Comment by danielt3** [comment]
Or the problem can be the fact that I'm using HTTPS (not SSH to push). Some organizations don't allow core developers to use HTTPS, only SSH for pushing and other stuff.

**Comment by danielt3** [comment]
Changing the remote to SSH instead of HTTPS didn't work.
```
johndoe@debian-generic:~/devel/openbor-git$ git remote -v
origin	git@github.com:DCurrent/openbor.git (fetch)
origin	git@github.com:DCurrent/openbor.git (push)
johndoe@debian-generic:~/devel/openbor-git$ git status
On branch fix-gcc9-build-breaks
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	engine/openbor.geany

nothing added to commit but untracked files present (use "git add" to track)
johndoe@debian-generic:~/devel/openbor-git$ git push -u origin fix-gcc9-build-breaks 
ERROR: Permission to DCurrent/openbor.git denied to danielt3.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
johndoe@debian-generic:~/devel/openbor-git$ 
```

**Comment by DCurrent** [comment]
@danielt3 Looking into this again. I'm kind of stumped to be honest, will keep poking around to see what I can figure out.

**Comment by DCurrent** [comment]
@danielt3 I believe I see the problem. I sent you an invite to collaborate, but you haven't accepted it yet. 

![image](https://user-images.githubusercontent.com/5900142/86261335-6c005c80-bb8c-11ea-81ad-24dc4abadd6a.png)

You need to check your email and accept the invitation.

**Comment by danielt3** [comment]
OMG. I'm so sorry about this. Well, Github didn't say anything regarding this apart from the e-mail itself (which I found). Well, after making this mistake I can only ask you to kindly resend the invitation (it only lasts for 7 days). I promise I won't miss it again and I'm really really sorry about my mistake. I hope I can make it up with great things for OpenBOR.

**Comment by DCurrent** [comment]
@danielt3 no problem friend. I'm out on the trail right now. When I get back I'll send you a new one.

**Comment by DCurrent** [comment]
@danielt3 I sent a new invite. Let me know if it works for you. Also, please sign up at www.chronocrash.com and review the development policies.

**Comment by danielt3** [comment]
Now I can push a branch! Thank you so much! Github has done a great job hiding the invitation in some obscure menu.

**Comment by danielt3** [comment]
For now, the only solution to this issue is to install an older GCC version. I think GCC <= 7 is enough.

**Comment by DCurrent** [comment]
Closing ticket as temporary solution was found and ancillary problems fixed.
